version: '3'

services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: snapshots
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongodata:/data/db
      - ./mongo-sensors-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  react:
    container_name: react
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - './app:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
  uvicorn:
    container_name: uvicorn
    build:
      context: .
      dockerfile: ./api/Dockerfile
    volumes:
      - './api:/app'
    ports:
      - 3002:80
