
#define MOTOR_PIN 2 // D4
#define MOTOR_SPEED_DEFAULT 1500
#define MOTOR_SPEED_FORWARD 1540
#define MOTOR_SPEED_BACK 1440

#define SERVO_PIN 12 // D6
#define SERVO_ANGLE_DEFAULT 90
#define SERVO_ANGLE_LEFT 120
#define SERVO_ANGLE_RIGHT 60

// Yellow - D2, Grey - D1
#define LEFT_SENSOR_PIN 3
#define LEFT_CENTER_SENSOR_PIN 4
#define RIGHT_SENSOR_PIN 5
#define RIGHT_CENTER_SENSOR_PIN 6
