
#define MOTOR_PIN 2
#define MOTOR_SPEED_DEFAULT 1500
#define MOTOR_SPEED_FORWARD 1540
#define MOTOR_SPEED_BACK 1440

#define SERVO_PIN 12
#define SERVO_ANGLE_DEFAULT 90
#define SERVO_ANGLE_LEFT 125
#define SERVO_ANGLE_RIGHT 60

#define LEFT_SENSOR_PIN 3
#define LEFT_CENTER_SENSOR_PIN 4
#define RIGHT_SENSOR_PIN 5
#define RIGHT_CENTER_SENSOR_PIN 6
